version: '3'
services:
  api:
    image: tunnelerapi
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8000:8000
    environment:
      - "BASEHREF=openbalenainstance.com"
      - "PUBLIC=192.168.1.200"