version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    command: 
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAILADDRESS}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "acme:/acme"
    networks:
      - web
    restart: always
  api:
    image: razikus/open-balena-tunneler:api-latest
    restart: always
    environment:
      - "BASEHREF=${OPENBALENAINSTANCE}"
      - "PUBLIC=${PUBLICIP}"
      - "IMAGENAME=razikus/open-balena-dashboard:tunneler-latest"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.api.rule=Host(`${DOMAINAPI}`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=letsencrypt
    networks:
      - web

networks:
  web:
    external: true
volumes:
  acme:
