name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./api/
          file: ./api/Dockerfile.template
          push: true
          tags: razikus/open-balena-tunneler:api-latest
          build-args: |
            BALENA_MACHINE_NAME=qemux86-64
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Build and push tunneler
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./tunneler/
          file: ./tunneler/Dockerfile.template
          push: true
          tags: razikus/open-balena-tunneler:tunneler-latest
          build-args: |
            BALENA_MACHINE_NAME=qemux86-64
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
